version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pingvinek-mars-frontend
    ports:
      - "3000:80"
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: pingvinek-mars-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pingvinek
      MONGO_INITDB_ROOT_PASSWORD: "h,]>X2EB93X'K(4X}ST£3KVxAn<)OKuWvvA>;2.Wm1uhg)?&}"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pingvinek-mars-backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: unless-stopped
  
  redis:
      image: redis:latest
      container_name: pingvinek-mars-redis
      environment:
        TZ: Europe/Budapest
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      restart: unless-stopped

volumes:
  mongodb_data:
  redis_data: